# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(734, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.step3_qtb = QtWidgets.QPushButton(self.centralwidget)
        self.step3_qtb.setCheckable(True)
        self.step3_qtb.setObjectName("step3_qtb")
        self.gridLayout_9.addWidget(self.step3_qtb, 4, 0, 1, 1)
        self.step2_qtb = QtWidgets.QPushButton(self.centralwidget)
        self.step2_qtb.setEnabled(True)
        self.step2_qtb.setCheckable(True)
        self.step2_qtb.setObjectName("step2_qtb")
        self.gridLayout_9.addWidget(self.step2_qtb, 3, 0, 1, 1)
        self.step1_qtb = QtWidgets.QPushButton(self.centralwidget)
        self.step1_qtb.setCheckable(True)
        self.step1_qtb.setObjectName("step1_qtb")
        self.gridLayout_9.addWidget(self.step1_qtb, 2, 0, 1, 1)
        self.updateexcel_qpb = QtWidgets.QPushButton(self.centralwidget)
        self.updateexcel_qpb.setStyleSheet("")
        self.updateexcel_qpb.setCheckable(True)
        self.updateexcel_qpb.setObjectName("updateexcel_qpb")
        self.gridLayout_9.addWidget(self.updateexcel_qpb, 1, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_9, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 214, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem, 2, 0, 1, 1)
        self.outshow_qte = QtWidgets.QTextEdit(self.centralwidget)
        self.outshow_qte.setObjectName("outshow_qte")
        self.gridLayout_8.addWidget(self.outshow_qte, 3, 0, 1, 2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.textEdit = QtWidgets.QTextEdit(self.page_6)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_17.addWidget(self.textEdit, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_6)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.funs_treeWidget = QtWidgets.QTreeWidget(self.page_4)
        self.funs_treeWidget.setObjectName("funs_treeWidget")
        self.funs_treeWidget.headerItem().setText(0, "1")
        self.gridLayout_2.addWidget(self.funs_treeWidget, 4, 7, 5, 3)
        self.test_engineer_qle = QtWidgets.QLineEdit(self.page_4)
        self.test_engineer_qle.setObjectName("test_engineer_qle")
        self.gridLayout_2.addWidget(self.test_engineer_qle, 0, 8, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.page_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 6, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.page_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.development_engineer_qle = QtWidgets.QLineEdit(self.page_4)
        self.development_engineer_qle.setObjectName("development_engineer_qle")
        self.gridLayout_2.addWidget(self.development_engineer_qle, 0, 2, 1, 4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.parseheaderfile_qpb = QtWidgets.QPushButton(self.page_4)
        self.parseheaderfile_qpb.setObjectName("parseheaderfile_qpb")
        self.verticalLayout.addWidget(self.parseheaderfile_qpb)
        self.label = QtWidgets.QLabel(self.page_4)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.filter_functions_qle = QtWidgets.QLineEdit(self.page_4)
        self.filter_functions_qle.setObjectName("filter_functions_qle")
        self.verticalLayout.addWidget(self.filter_functions_qle)
        self.funs_qlw = QtWidgets.QListWidget(self.page_4)
        self.funs_qlw.setObjectName("funs_qlw")
        self.verticalLayout.addWidget(self.funs_qlw)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 0, 7, 4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 2, 7, 1, 3)
        self.deleteFromTreeWidegt_qpb = QtWidgets.QToolButton(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteFromTreeWidegt_qpb.sizePolicy().hasHeightForWidth())
        self.deleteFromTreeWidegt_qpb.setSizePolicy(sizePolicy)
        self.deleteFromTreeWidegt_qpb.setMinimumSize(QtCore.QSize(85, 0))
        self.deleteFromTreeWidegt_qpb.setObjectName("deleteFromTreeWidegt_qpb")
        self.gridLayout_2.addWidget(self.deleteFromTreeWidegt_qpb, 6, 5, 1, 2)
        self.update_excelinfo_qpb = QtWidgets.QPushButton(self.page_4)
        self.update_excelinfo_qpb.setObjectName("update_excelinfo_qpb")
        self.gridLayout_2.addWidget(self.update_excelinfo_qpb, 8, 5, 1, 2)
        self.importToTreeWidegt_qpb = QtWidgets.QToolButton(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importToTreeWidegt_qpb.sizePolicy().hasHeightForWidth())
        self.importToTreeWidegt_qpb.setSizePolicy(sizePolicy)
        self.importToTreeWidegt_qpb.setMinimumSize(QtCore.QSize(85, 0))
        self.importToTreeWidegt_qpb.setObjectName("importToTreeWidegt_qpb")
        self.gridLayout_2.addWidget(self.importToTreeWidegt_qpb, 5, 5, 1, 2)
        self.addPageName_qle = QtWidgets.QLineEdit(self.page_4)
        self.addPageName_qle.setMinimumSize(QtCore.QSize(85, 0))
        self.addPageName_qle.setObjectName("addPageName_qle")
        self.gridLayout_2.addWidget(self.addPageName_qle, 3, 7, 1, 2)
        self.addOtherPage_qpb = QtWidgets.QPushButton(self.page_4)
        self.addOtherPage_qpb.setObjectName("addOtherPage_qpb")
        self.gridLayout_2.addWidget(self.addOtherPage_qpb, 3, 9, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(85, 65, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 2, 5, 3, 2)
        spacerItem4 = QtWidgets.QSpacerItem(85, 102, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 7, 5, 1, 2)
        self.copyexcelmodel_qtb = QtWidgets.QPushButton(self.page_4)
        self.copyexcelmodel_qtb.setObjectName("copyexcelmodel_qtb")
        self.gridLayout_2.addWidget(self.copyexcelmodel_qtb, 1, 9, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(180, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 0, 1, 9)
        self.stackedWidget.addWidget(self.page_4)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_9)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_9)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_10.addWidget(self.lineEdit_3, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(556, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem6, 2, 0, 1, 1)
        self.filebtn_1 = QtWidgets.QPushButton(self.page_9)
        self.filebtn_1.setMinimumSize(QtCore.QSize(70, 0))
        self.filebtn_1.setObjectName("filebtn_1")
        self.gridLayout_10.addWidget(self.filebtn_1, 1, 1, 1, 1)
        self.xlsfileName_qle = QtWidgets.QLineEdit(self.page_9)
        self.xlsfileName_qle.setObjectName("xlsfileName_qle")
        self.gridLayout_10.addWidget(self.xlsfileName_qle, 1, 0, 1, 1)
        self.check_requirement_qpb = QtWidgets.QPushButton(self.page_9)
        self.check_requirement_qpb.setMinimumSize(QtCore.QSize(130, 0))
        self.check_requirement_qpb.setMaximumSize(QtCore.QSize(300, 16777215))
        self.check_requirement_qpb.setObjectName("check_requirement_qpb")
        self.gridLayout_10.addWidget(self.check_requirement_qpb, 2, 1, 1, 1)
        self.tabWidget_xuqiu_qtw = QtWidgets.QTabWidget(self.page_9)
        self.tabWidget_xuqiu_qtw.setObjectName("tabWidget_xuqiu_qtw")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.resultOutput_qte = QtWidgets.QTextEdit(self.tab_1)
        self.resultOutput_qte.setObjectName("resultOutput_qte")
        self.gridLayout_12.addWidget(self.resultOutput_qte, 1, 0, 1, 2)
        self.tabWidget_xuqiu_qtw.addTab(self.tab_1, "")
        self.gridLayout_10.addWidget(self.tabWidget_xuqiu_qtw, 4, 0, 1, 3)
        self.stackedWidget.addWidget(self.page_9)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.page_2)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.excelcollectPath_qle = QtWidgets.QLineEdit(self.tab_5)
        self.excelcollectPath_qle.setObjectName("excelcollectPath_qle")
        self.gridLayout_11.addWidget(self.excelcollectPath_qle, 0, 0, 1, 4)
        self.excelcollect_btn = QtWidgets.QPushButton(self.tab_5)
        self.excelcollect_btn.setMinimumSize(QtCore.QSize(120, 0))
        self.excelcollect_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        self.excelcollect_btn.setObjectName("excelcollect_btn")
        self.gridLayout_11.addWidget(self.excelcollect_btn, 0, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem7, 1, 0, 1, 1)
        self.collect_requirement_info_qpb = QtWidgets.QPushButton(self.tab_5)
        self.collect_requirement_info_qpb.setObjectName("collect_requirement_info_qpb")
        self.gridLayout_11.addWidget(self.collect_requirement_info_qpb, 1, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(89, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem8, 1, 2, 1, 1)
        self.closeExcel_qpb = QtWidgets.QPushButton(self.tab_5)
        self.closeExcel_qpb.setObjectName("closeExcel_qpb")
        self.gridLayout_11.addWidget(self.closeExcel_qpb, 1, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(117, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem9, 1, 4, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_11.addWidget(self.lineEdit, 2, 0, 1, 1)
        self.resultOutput_qte2 = QtWidgets.QTextEdit(self.tab_5)
        self.resultOutput_qte2.setObjectName("resultOutput_qte2")
        self.gridLayout_11.addWidget(self.resultOutput_qte2, 3, 0, 1, 5)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.funsToExcelXml_qtb = QtWidgets.QPushButton(self.groupBox_2)
        self.funsToExcelXml_qtb.setObjectName("funsToExcelXml_qtb")
        self.verticalLayout_4.addWidget(self.funsToExcelXml_qtb)
        self.createExcelsheet_qpb = QtWidgets.QPushButton(self.groupBox_2)
        self.createExcelsheet_qpb.setObjectName("createExcelsheet_qpb")
        self.verticalLayout_4.addWidget(self.createExcelsheet_qpb)
        self.gridLayout_4.addWidget(self.groupBox_2, 4, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem10, 5, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem11, 0, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem12, 3, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.displayfunsInfo_qpb = QtWidgets.QPushButton(self.page_3)
        self.displayfunsInfo_qpb.setObjectName("displayfunsInfo_qpb")
        self.verticalLayout_3.addWidget(self.displayfunsInfo_qpb)
        self.headFileProcess_qpb = QtWidgets.QPushButton(self.page_3)
        self.headFileProcess_qpb.setObjectName("headFileProcess_qpb")
        self.verticalLayout_3.addWidget(self.headFileProcess_qpb)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.headfilespath_qtb = QtWidgets.QTableWidget(self.page_3)
        self.headfilespath_qtb.setObjectName("headfilespath_qtb")
        self.headfilespath_qtb.setColumnCount(2)
        self.headfilespath_qtb.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.headfilespath_qtb.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.headfilespath_qtb.setHorizontalHeaderItem(1, item)
        self.gridLayout_4.addWidget(self.headfilespath_qtb, 0, 0, 6, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout.setObjectName("gridLayout")
        self.xmlindex_qcb = QtWidgets.QComboBox(self.page_5)
        self.xmlindex_qcb.setObjectName("xmlindex_qcb")
        self.xmlindex_qcb.addItem("")
        self.xmlindex_qcb.addItem("")
        self.gridLayout.addWidget(self.xmlindex_qcb, 0, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(464, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 0, 1, 1, 1)
        self.generate_xmlfile_qpb = QtWidgets.QPushButton(self.page_5)
        self.generate_xmlfile_qpb.setObjectName("generate_xmlfile_qpb")
        self.gridLayout.addWidget(self.generate_xmlfile_qpb, 0, 2, 1, 1)
        self.xmldisplay_qte = QtWidgets.QTextEdit(self.page_5)
        self.xmldisplay_qte.setObjectName("xmldisplay_qte")
        self.gridLayout.addWidget(self.xmldisplay_qte, 1, 0, 1, 3)
        self.stackedWidget.addWidget(self.page_5)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem14 = QtWidgets.QSpacerItem(20, 134, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem14, 0, 1, 1, 1)
        self.parse_excelFunsXml_qpb = QtWidgets.QPushButton(self.page_7)
        self.parse_excelFunsXml_qpb.setObjectName("parse_excelFunsXml_qpb")
        self.gridLayout_7.addWidget(self.parse_excelFunsXml_qpb, 1, 1, 1, 1)
        self.generateUniversalvtfile_qpb = QtWidgets.QPushButton(self.page_7)
        self.generateUniversalvtfile_qpb.setObjectName("generateUniversalvtfile_qpb")
        self.gridLayout_7.addWidget(self.generateUniversalvtfile_qpb, 2, 1, 1, 1)
        self.generator_headfiles_qpb = QtWidgets.QPushButton(self.page_7)
        self.generator_headfiles_qpb.setObjectName("generator_headfiles_qpb")
        self.gridLayout_7.addWidget(self.generator_headfiles_qpb, 3, 1, 1, 1)
        self.parse_excelXmlForUi_qpb = QtWidgets.QPushButton(self.page_7)
        self.parse_excelXmlForUi_qpb.setObjectName("parse_excelXmlForUi_qpb")
        self.gridLayout_7.addWidget(self.parse_excelXmlForUi_qpb, 4, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 133, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem15, 5, 1, 1, 1)
        self.cppfiles_qte = QtWidgets.QTextEdit(self.page_7)
        self.cppfiles_qte.setObjectName("cppfiles_qte")
        self.gridLayout_7.addWidget(self.cppfiles_qte, 0, 0, 6, 1)
        self.stackedWidget.addWidget(self.page_7)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.tabWidget_excel = QtWidgets.QTabWidget(self.page)
        self.tabWidget_excel.setObjectName("tabWidget_excel")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tw_excelsheet1_out = QtWidgets.QTableWidget(self.tab_4)
        self.tw_excelsheet1_out.setObjectName("tw_excelsheet1_out")
        self.tw_excelsheet1_out.setColumnCount(6)
        self.tw_excelsheet1_out.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_excelsheet1_out.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_excelsheet1_out.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_excelsheet1_out.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_excelsheet1_out.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_excelsheet1_out.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_excelsheet1_out.setHorizontalHeaderItem(5, item)
        self.gridLayout_5.addWidget(self.tw_excelsheet1_out, 0, 0, 1, 1)
        self.tabWidget_excel.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.tw_excelsheet2_out = QtWidgets.QTableWidget(self.tab_6)
        self.tw_excelsheet2_out.setObjectName("tw_excelsheet2_out")
        self.tw_excelsheet2_out.setColumnCount(12)
        self.tw_excelsheet2_out.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_excelsheet2_out.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_excelsheet2_out.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_excelsheet2_out.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_excelsheet2_out.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_excelsheet2_out.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_excelsheet2_out.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_excelsheet2_out.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_excelsheet2_out.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_excelsheet2_out.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_excelsheet2_out.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_excelsheet2_out.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_excelsheet2_out.setHorizontalHeaderItem(11, item)
        self.gridLayout_16.addWidget(self.tw_excelsheet2_out, 0, 0, 1, 1)
        self.tabWidget_excel.addTab(self.tab_6, "")
        self.gridLayout_14.addWidget(self.tabWidget_excel, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem16)
        self.checkexcelui_qpb = QtWidgets.QPushButton(self.page)
        self.checkexcelui_qpb.setObjectName("checkexcelui_qpb")
        self.horizontalLayout_3.addWidget(self.checkexcelui_qpb)
        self.writeToExcel_qpb = QtWidgets.QPushButton(self.page)
        self.writeToExcel_qpb.setObjectName("writeToExcel_qpb")
        self.horizontalLayout_3.addWidget(self.writeToExcel_qpb)
        self.addenum_qpb = QtWidgets.QPushButton(self.page)
        self.addenum_qpb.setObjectName("addenum_qpb")
        self.horizontalLayout_3.addWidget(self.addenum_qpb)
        self.gridLayout_14.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.gridLayout_8.addWidget(self.stackedWidget, 0, 1, 3, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 734, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.tabWidget_xuqiu_qtw.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_excel.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.step3_qtb.setText(_translate("MainWindow", "step3 生成代码/界面文件"))
        self.step2_qtb.setText(_translate("MainWindow", "step2 生成xml文件"))
        self.step1_qtb.setText(_translate("MainWindow", "step1 收集表格信息"))
        self.updateexcel_qpb.setText(_translate("MainWindow", "1需求表格更新"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">需求表格更新：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\"> 适用于第一次开发VTXX页面时，创建需求表格。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\"> 和有接口变更时，用于需求表格更新。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt; font-weight:600; color:#008080;\">关于单位：<br /> 1、参数如果没有单位，填none,防止有单位的参数漏填<br /> 2、有单位，判断是否是国际单位，是则警告。<br />关于数据类型：<br /> 1、使用SMEE内置单位，SMEE_BOOL,SMEE_FLOAT,SMEE_DOUBLE,...<br />关于精度、步长、默认值：<br /> 1、如果没有指定，整型为0,浮点型为6，其他补none.<br /> 2、输入参数，有范围，步长整形为1，其他步长根据精度确定。<br /> 3、输出参数，默认值一律填none。<br /> 4、输入参数，有参数范围的，按实际需求填写。没有要求的，一律none。<br /> 5、默认值在参数范围区间内。<br />关于参数范围：<br /> 1、只有输入参数才有范围，没有范围补none。<br /> 2、输出范围，脚本一律自动补none。<br />关于参数标签：<br /> 1、单词首字母大写，空格隔开，专有名词按实际填写。<br />关于需求表格书写：<br /> 1、不到最后一行，不能有空行<br /> 2、接口无参数时同样要保留信息。<br />关于接口样式：<br />  SMEE_EXPORT  SMEE_INT32  LB4A_set_spots_valid(IN LB4A_FOCUS_TYPE_ENUM eFSFocusType,<br />                                             IN LB4A_SPOTS_VALID_STRUCT *pstSpotsValid);对</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "测试人员姓名"))
        self.label_5.setText(_translate("MainWindow", "开发人员姓名"))
        self.lineEdit_4.setText(_translate("MainWindow", "需求表格中的接口列表如下："))
        self.parseheaderfile_qpb.setText(_translate("MainWindow", "获取接口列表"))
        self.label.setText(_translate("MainWindow", "搜索框:"))
        self.lineEdit_5.setText(_translate("MainWindow", "接口在界面布局信息如下："))
        self.deleteFromTreeWidegt_qpb.setText(_translate("MainWindow", "<<<"))
        self.update_excelinfo_qpb.setText(_translate("MainWindow", "确定"))
        self.importToTreeWidegt_qpb.setText(_translate("MainWindow", ">>>"))
        self.addOtherPage_qpb.setText(_translate("MainWindow", "Add Page"))
        self.copyexcelmodel_qtb.setText(_translate("MainWindow", "拷贝需求表格模板"))
        self.lineEdit_3.setText(_translate("MainWindow", "请选择需要检查的需求表格路径："))
        self.filebtn_1.setText(_translate("MainWindow", "选择"))
        self.check_requirement_qpb.setText(_translate("MainWindow", "检查需求表格规范"))
        self.resultOutput_qte.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget_xuqiu_qtw.setTabText(self.tabWidget_xuqiu_qtw.indexOf(self.tab_1), _translate("MainWindow", "需求表格检查结果"))
        self.excelcollect_btn.setText(_translate("MainWindow", "选择需求表格"))
        self.collect_requirement_info_qpb.setText(_translate("MainWindow", "收集需求表格信息"))
        self.closeExcel_qpb.setText(_translate("MainWindow", "补充枚举信息"))
        self.lineEdit.setText(_translate("MainWindow", "需求表格信息显示："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "需求表格信息"))
        self.funsToExcelXml_qtb.setText(_translate("MainWindow", "8funsInfoToExcel.xml"))
        self.createExcelsheet_qpb.setText(_translate("MainWindow", "完善需求表格信息"))
        self.displayfunsInfo_qpb.setText(_translate("MainWindow", "显示头文件列表"))
        self.headFileProcess_qpb.setText(_translate("MainWindow", "头文件预处理"))
        item = self.headfilespath_qtb.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "所需头文件列表："))
        item = self.headfilespath_qtb.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "头文件本地路径："))
        self.xmlindex_qcb.setItemText(0, _translate("MainWindow", "10excelFunsForCpp"))
        self.xmlindex_qcb.setItemText(1, _translate("MainWindow", "11excelXmlForUi"))
        self.generate_xmlfile_qpb.setText(_translate("MainWindow", "生成xml文件"))
        self.parse_excelFunsXml_qpb.setText(_translate("MainWindow", "解析10excelFunsForCpp"))
        self.generateUniversalvtfile_qpb.setText(_translate("MainWindow", "生成通用代码文件"))
        self.generator_headfiles_qpb.setText(_translate("MainWindow", "生成各页面头文件"))
        self.parse_excelXmlForUi_qpb.setText(_translate("MainWindow", "解析11excelXmlForUi"))
        item = self.tw_excelsheet1_out.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "页面名称"))
        item = self.tw_excelsheet1_out.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "一级Tab页标签"))
        item = self.tw_excelsheet1_out.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "二级Tab页标签"))
        item = self.tw_excelsheet1_out.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "功能标签"))
        item = self.tw_excelsheet1_out.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "功能函数"))
        item = self.tw_excelsheet1_out.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "备注"))
        self.tabWidget_excel.setTabText(self.tabWidget_excel.indexOf(self.tab_4), _translate("MainWindow", "界面布局"))
        item = self.tw_excelsheet2_out.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "功能函数"))
        item = self.tw_excelsheet2_out.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "参数"))
        item = self.tw_excelsheet2_out.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "输入/输出"))
        item = self.tw_excelsheet2_out.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "参数标签"))
        item = self.tw_excelsheet2_out.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "参数类型"))
        item = self.tw_excelsheet2_out.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "单位"))
        item = self.tw_excelsheet2_out.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "默认值"))
        item = self.tw_excelsheet2_out.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "精度"))
        item = self.tw_excelsheet2_out.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "范围"))
        item = self.tw_excelsheet2_out.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "步长"))
        item = self.tw_excelsheet2_out.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "单位转换"))
        item = self.tw_excelsheet2_out.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "备注"))
        self.tabWidget_excel.setTabText(self.tabWidget_excel.indexOf(self.tab_6), _translate("MainWindow", "界面参数配置"))
        self.checkexcelui_qpb.setText(_translate("MainWindow", "规范检查"))
        self.writeToExcel_qpb.setText(_translate("MainWindow", "写到需求表格"))
        self.addenum_qpb.setText(_translate("MainWindow", "补充枚举到需求表格"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

