# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(815, 388)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.step3_qtb = QtWidgets.QPushButton(self.centralwidget)
        self.step3_qtb.setCheckable(True)
        self.step3_qtb.setObjectName("step3_qtb")
        self.gridLayout_9.addWidget(self.step3_qtb, 3, 0, 1, 1)
        self.step7_qtb = QtWidgets.QPushButton(self.centralwidget)
        self.step7_qtb.setCheckable(True)
        self.step7_qtb.setObjectName("step7_qtb")
        self.gridLayout_9.addWidget(self.step7_qtb, 5, 0, 1, 1)
        self.step1_qtb = QtWidgets.QPushButton(self.centralwidget)
        self.step1_qtb.setCheckable(True)
        self.step1_qtb.setChecked(False)
        self.step1_qtb.setObjectName("step1_qtb")
        self.gridLayout_9.addWidget(self.step1_qtb, 1, 0, 1, 1)
        self.step5_qtb = QtWidgets.QPushButton(self.centralwidget)
        self.step5_qtb.setCheckable(True)
        self.step5_qtb.setObjectName("step5_qtb")
        self.gridLayout_9.addWidget(self.step5_qtb, 4, 0, 1, 1)
        self.prepare_qtb = QtWidgets.QPushButton(self.centralwidget)
        self.prepare_qtb.setCheckable(True)
        self.prepare_qtb.setChecked(True)
        self.prepare_qtb.setObjectName("prepare_qtb")
        self.gridLayout_9.addWidget(self.prepare_qtb, 0, 0, 1, 1)
        self.step8_qtb = QtWidgets.QPushButton(self.centralwidget)
        self.step8_qtb.setCheckable(True)
        self.step8_qtb.setObjectName("step8_qtb")
        self.gridLayout_9.addWidget(self.step8_qtb, 6, 0, 1, 1)
        self.step2_qtb = QtWidgets.QPushButton(self.centralwidget)
        self.step2_qtb.setCheckable(True)
        self.step2_qtb.setObjectName("step2_qtb")
        self.gridLayout_9.addWidget(self.step2_qtb, 2, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_9)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_2 = QtWidgets.QLabel(self.page_9)
        self.label_2.setObjectName("label_2")
        self.gridLayout_10.addWidget(self.label_2, 0, 0, 1, 1)
        self.projectName_qle = QtWidgets.QLineEdit(self.page_9)
        self.projectName_qle.setObjectName("projectName_qle")
        self.gridLayout_10.addWidget(self.projectName_qle, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page_9)
        self.label_3.setObjectName("label_3")
        self.gridLayout_10.addWidget(self.label_3, 0, 2, 1, 1)
        self.componentName_qle = QtWidgets.QLineEdit(self.page_9)
        self.componentName_qle.setObjectName("componentName_qle")
        self.gridLayout_10.addWidget(self.componentName_qle, 0, 3, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.page_9)
        self.label_5.setObjectName("label_5")
        self.gridLayout_10.addWidget(self.label_5, 1, 0, 1, 1)
        self.development_engineer_qle = QtWidgets.QLineEdit(self.page_9)
        self.development_engineer_qle.setObjectName("development_engineer_qle")
        self.gridLayout_10.addWidget(self.development_engineer_qle, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page_9)
        self.label_6.setObjectName("label_6")
        self.gridLayout_10.addWidget(self.label_6, 1, 2, 1, 1)
        self.test_engineer_qle = QtWidgets.QLineEdit(self.page_9)
        self.test_engineer_qle.setObjectName("test_engineer_qle")
        self.gridLayout_10.addWidget(self.test_engineer_qle, 1, 3, 1, 2)
        self.label = QtWidgets.QLabel(self.page_9)
        self.label.setObjectName("label")
        self.gridLayout_10.addWidget(self.label, 2, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(151, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem, 2, 3, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.page_9)
        self.label_4.setObjectName("label_4")
        self.gridLayout_10.addWidget(self.label_4, 3, 0, 1, 1)
        self.tempdir_qpb = QtWidgets.QPushButton(self.page_9)
        self.tempdir_qpb.setMinimumSize(QtCore.QSize(100, 0))
        self.tempdir_qpb.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tempdir_qpb.setObjectName("tempdir_qpb")
        self.gridLayout_10.addWidget(self.tempdir_qpb, 4, 3, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(485, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem1, 5, 0, 1, 3)
        self.createTempDir_qpb = QtWidgets.QPushButton(self.page_9)
        self.createTempDir_qpb.setObjectName("createTempDir_qpb")
        self.gridLayout_10.addWidget(self.createTempDir_qpb, 5, 3, 1, 2)
        self.filebtn_1 = QtWidgets.QPushButton(self.page_9)
        self.filebtn_1.setMinimumSize(QtCore.QSize(70, 0))
        self.filebtn_1.setObjectName("filebtn_1")
        self.gridLayout_10.addWidget(self.filebtn_1, 7, 3, 1, 1)
        self.copy_xlsfile_to_tempdir_qpb = QtWidgets.QPushButton(self.page_9)
        self.copy_xlsfile_to_tempdir_qpb.setObjectName("copy_xlsfile_to_tempdir_qpb")
        self.gridLayout_10.addWidget(self.copy_xlsfile_to_tempdir_qpb, 7, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(518, 171, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem2, 8, 0, 1, 5)
        self.tempdir_qle = QtWidgets.QLineEdit(self.page_9)
        self.tempdir_qle.setObjectName("tempdir_qle")
        self.gridLayout_10.addWidget(self.tempdir_qle, 4, 0, 1, 3)
        self.xlsfileName_qle = QtWidgets.QLineEdit(self.page_9)
        self.xlsfileName_qle.setObjectName("xlsfileName_qle")
        self.gridLayout_10.addWidget(self.xlsfileName_qle, 7, 0, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem3, 6, 2, 1, 3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_9)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_10.addWidget(self.lineEdit_3, 6, 0, 1, 2)
        self.stackedWidget.addWidget(self.page_9)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.tabWidget_xuqiu_qtw = QtWidgets.QTabWidget(self.page)
        self.tabWidget_xuqiu_qtw.setObjectName("tabWidget_xuqiu_qtw")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.check_requirement_qpb = QtWidgets.QPushButton(self.tab_1)
        self.check_requirement_qpb.setMinimumSize(QtCore.QSize(130, 0))
        self.check_requirement_qpb.setMaximumSize(QtCore.QSize(300, 16777215))
        self.check_requirement_qpb.setObjectName("check_requirement_qpb")
        self.gridLayout_12.addWidget(self.check_requirement_qpb, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(556, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem4, 0, 1, 1, 1)
        self.resultOutput_qte = QtWidgets.QTextEdit(self.tab_1)
        self.resultOutput_qte.setObjectName("resultOutput_qte")
        self.gridLayout_12.addWidget(self.resultOutput_qte, 1, 0, 1, 2)
        self.tabWidget_xuqiu_qtw.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.requirement_rule_qte = QtWidgets.QTextEdit(self.tab_2)
        self.requirement_rule_qte.setObjectName("requirement_rule_qte")
        self.gridLayout_2.addWidget(self.requirement_rule_qte, 0, 0, 1, 1)
        self.tabWidget_xuqiu_qtw.addTab(self.tab_2, "")
        self.gridLayout_16.addWidget(self.tabWidget_xuqiu_qtw, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.tabWidget = QtWidgets.QTabWidget(self.page_2)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_2.addWidget(self.lineEdit_5)
        self.funs_treeWidget = QtWidgets.QTreeWidget(self.tab_4)
        self.funs_treeWidget.setObjectName("funs_treeWidget")
        self.funs_treeWidget.headerItem().setText(0, "1")
        self.verticalLayout_2.addWidget(self.funs_treeWidget)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem5)
        self.addPageName_qle = QtWidgets.QLineEdit(self.tab_4)
        self.addPageName_qle.setMinimumSize(QtCore.QSize(85, 0))
        self.addPageName_qle.setObjectName("addPageName_qle")
        self.verticalLayout_3.addWidget(self.addPageName_qle)
        self.addOtherPage_qpb = QtWidgets.QPushButton(self.tab_4)
        self.addOtherPage_qpb.setObjectName("addOtherPage_qpb")
        self.verticalLayout_3.addWidget(self.addOtherPage_qpb)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.importToTreeWidegt_qpb = QtWidgets.QToolButton(self.tab_4)
        self.importToTreeWidegt_qpb.setMinimumSize(QtCore.QSize(85, 0))
        self.importToTreeWidegt_qpb.setObjectName("importToTreeWidegt_qpb")
        self.verticalLayout_3.addWidget(self.importToTreeWidegt_qpb)
        self.deleteFromTreeWidegt_qpb = QtWidgets.QToolButton(self.tab_4)
        self.deleteFromTreeWidegt_qpb.setMinimumSize(QtCore.QSize(85, 0))
        self.deleteFromTreeWidegt_qpb.setObjectName("deleteFromTreeWidegt_qpb")
        self.verticalLayout_3.addWidget(self.deleteFromTreeWidegt_qpb)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.check_requirement_qpb2 = QtWidgets.QPushButton(self.tab_4)
        self.check_requirement_qpb2.setObjectName("check_requirement_qpb2")
        self.verticalLayout_3.addWidget(self.check_requirement_qpb2)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.funs_qlw = QtWidgets.QListWidget(self.tab_4)
        self.funs_qlw.setObjectName("funs_qlw")
        self.verticalLayout.addWidget(self.funs_qlw)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_14.addWidget(self.lineEdit, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(381, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem8, 0, 1, 1, 1)
        self.resultOutput_qte2 = QtWidgets.QTextEdit(self.tab_5)
        self.resultOutput_qte2.setObjectName("resultOutput_qte2")
        self.gridLayout_14.addWidget(self.resultOutput_qte2, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout_13.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.headFileProcess_qpb = QtWidgets.QPushButton(self.page_3)
        self.headFileProcess_qpb.setObjectName("headFileProcess_qpb")
        self.gridLayout_4.addWidget(self.headFileProcess_qpb, 2, 2, 1, 1)
        self.displayfunsInfo_qpb = QtWidgets.QPushButton(self.page_3)
        self.displayfunsInfo_qpb.setObjectName("displayfunsInfo_qpb")
        self.gridLayout_4.addWidget(self.displayfunsInfo_qpb, 0, 2, 1, 1)
        self.headfilespath_qtb = QtWidgets.QTableWidget(self.page_3)
        self.headfilespath_qtb.setObjectName("headfilespath_qtb")
        self.headfilespath_qtb.setColumnCount(2)
        self.headfilespath_qtb.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.headfilespath_qtb.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.headfilespath_qtb.setHorizontalHeaderItem(1, item)
        self.gridLayout_4.addWidget(self.headfilespath_qtb, 1, 0, 1, 3)
        spacerItem9 = QtWidgets.QSpacerItem(548, 96, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem9, 4, 0, 1, 3)
        spacerItem10 = QtWidgets.QSpacerItem(501, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 2, 0, 1, 2)
        spacerItem11 = QtWidgets.QSpacerItem(441, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 0, 0, 1, 2)
        self.addenum_qpb = QtWidgets.QPushButton(self.page_3)
        self.addenum_qpb.setObjectName("addenum_qpb")
        self.gridLayout_4.addWidget(self.addenum_qpb, 3, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem13 = QtWidgets.QSpacerItem(535, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem13, 0, 0, 1, 1)
        self.generate_xmlfile_qpb = QtWidgets.QPushButton(self.page_5)
        self.generate_xmlfile_qpb.setObjectName("generate_xmlfile_qpb")
        self.gridLayout_5.addWidget(self.generate_xmlfile_qpb, 0, 1, 1, 1)
        self.xmlindex_qcb = QtWidgets.QComboBox(self.page_5)
        self.xmlindex_qcb.setObjectName("xmlindex_qcb")
        self.xmlindex_qcb.addItem("")
        self.xmlindex_qcb.addItem("")
        self.gridLayout_5.addWidget(self.xmlindex_qcb, 1, 0, 1, 2)
        self.xmldisplay_qte = QtWidgets.QTextEdit(self.page_5)
        self.xmldisplay_qte.setObjectName("xmldisplay_qte")
        self.gridLayout_5.addWidget(self.xmldisplay_qte, 2, 0, 1, 2)
        self.stackedWidget.addWidget(self.page_5)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem14 = QtWidgets.QSpacerItem(464, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem14, 0, 0, 1, 1)
        self.generateUniversalvtfile_qpb = QtWidgets.QPushButton(self.page_7)
        self.generateUniversalvtfile_qpb.setObjectName("generateUniversalvtfile_qpb")
        self.gridLayout_7.addWidget(self.generateUniversalvtfile_qpb, 0, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(476, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem15, 1, 0, 1, 1)
        self.generator_headfiles_qpb = QtWidgets.QPushButton(self.page_7)
        self.generator_headfiles_qpb.setObjectName("generator_headfiles_qpb")
        self.gridLayout_7.addWidget(self.generator_headfiles_qpb, 1, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(464, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem16, 2, 0, 1, 1)
        self.parse_excelFunsXml_qpb = QtWidgets.QPushButton(self.page_7)
        self.parse_excelFunsXml_qpb.setObjectName("parse_excelFunsXml_qpb")
        self.gridLayout_7.addWidget(self.parse_excelFunsXml_qpb, 2, 1, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.page_7)
        self.lineEdit_9.setEnabled(False)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_7.addWidget(self.lineEdit_9, 3, 0, 1, 2)
        self.cppfiles_qte = QtWidgets.QTextEdit(self.page_7)
        self.cppfiles_qte.setObjectName("cppfiles_qte")
        self.gridLayout_7.addWidget(self.cppfiles_qte, 4, 0, 1, 2)
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.gridLayout = QtWidgets.QGridLayout(self.page_8)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem17 = QtWidgets.QSpacerItem(458, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem17, 0, 0, 1, 1)
        self.parse_excelXmlForUi_qpb = QtWidgets.QPushButton(self.page_8)
        self.parse_excelXmlForUi_qpb.setObjectName("parse_excelXmlForUi_qpb")
        self.gridLayout.addWidget(self.parse_excelXmlForUi_qpb, 0, 1, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.page_8)
        self.lineEdit_10.setEnabled(False)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 1, 0, 1, 2)
        self.uifiles_qtb = QtWidgets.QTextEdit(self.page_8)
        self.uifiles_qtb.setObjectName("uifiles_qtb")
        self.gridLayout.addWidget(self.uifiles_qtb, 2, 0, 1, 2)
        self.stackedWidget.addWidget(self.page_8)
        self.gridLayout_15.addWidget(self.stackedWidget, 0, 1, 2, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 106, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem18, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(6)
        self.tabWidget_xuqiu_qtw.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.step3_qtb.setText(_translate("MainWindow", "step3 收集接口信息"))
        self.step7_qtb.setText(_translate("MainWindow", "step7 生成代码文件"))
        self.step1_qtb.setText(_translate("MainWindow", "step1 检查需求表格规范"))
        self.step5_qtb.setText(_translate("MainWindow", "step5 生成xml文件"))
        self.prepare_qtb.setText(_translate("MainWindow", "准备工作"))
        self.step8_qtb.setText(_translate("MainWindow", "step8 生成界面文件"))
        self.step2_qtb.setText(_translate("MainWindow", "step2 收集表格信息"))
        self.label_2.setText(_translate("MainWindow", "项目名（eg:506，301c）："))
        self.label_3.setText(_translate("MainWindow", "组件名(eg:AE,WS)："))
        self.label_5.setText(_translate("MainWindow", "开发人员姓名："))
        self.label_6.setText(_translate("MainWindow", "测试人员姓名："))
        self.label.setText(_translate("MainWindow", "创建临时文件夹，存放生成的中间处理文件(文件夹格式：temp_项目名+\'VT\'+组件名)："))
        self.label_4.setText(_translate("MainWindow", "请选择创建文件夹的位置"))
        self.tempdir_qpb.setText(_translate("MainWindow", "No.1 选择"))
        self.createTempDir_qpb.setText(_translate("MainWindow", "No.2 创建文件夹"))
        self.filebtn_1.setText(_translate("MainWindow", "No.3 选择"))
        self.copy_xlsfile_to_tempdir_qpb.setText(_translate("MainWindow", "No.4 copy"))
        self.lineEdit_3.setText(_translate("MainWindow", "请选择本地组件需求表格,自动拷贝到临时文件夹下："))
        self.check_requirement_qpb.setText(_translate("MainWindow", "检查需求表格规范"))
        self.resultOutput_qte.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget_xuqiu_qtw.setTabText(self.tabWidget_xuqiu_qtw.indexOf(self.tab_1), _translate("MainWindow", "需求表格检查结果"))
        self.requirement_rule_qte.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0b0b0b;\">关于单位：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-style:italic; color:#0b0b0b;\">1、</span><span style=\" color:#0b0b0b;\">参数如果没有单位，填写none,防止有单位的参数漏填</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0b0b0b;\">2、有单位，判断是否是国际单位。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0b0b0b;\">关于数据类型：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0b0b0b;\">1、使用SMEE内置单位，SMEE_BOOL,SMEE_FLOAT,SMEE_DOUBLE,...</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0b0b0b;\">关于精度：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0b0b0b;\">1、如果没有指定，整型为0,浮点型为6，其他补none.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0b0b0b;\">关于步长：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0b0b0b;\">1、输入参数，有范围，整形为1，其他根据精度确定。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0b0b0b;\">关于默认值：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0b0b0b;\">1、输出参数，默认值一律填none。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0b0b0b;\">2、输入参数，有参数范围的，按实际需求填写。没有要求的，一律none。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0b0b0b;\">3、默认值在参数范围区间内。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0b0b0b;\">关于参数范围：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0b0b0b;\">1、只有输入参数才有范围，没有范围补none。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0b0b0b;\">2、输出范围，脚本一律自动补none。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0b0b0b;\">关于参数标签：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0b0b0b;\">1、单词首字母大写，空格隔开，专有名词按实际填写。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0b0b0b;\">关于表格书写：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0b0b0b;\">1、不到最后一行，不能有空行</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0b0b0b;\">2、接口无参数时同样要保留信息。</span></p></body></html>"))
        self.tabWidget_xuqiu_qtw.setTabText(self.tabWidget_xuqiu_qtw.indexOf(self.tab_2), _translate("MainWindow", "需求表格规范约定"))
        self.lineEdit_5.setText(_translate("MainWindow", "接口在界面布局信息如下："))
        self.addOtherPage_qpb.setText(_translate("MainWindow", "Add Page"))
        self.importToTreeWidegt_qpb.setText(_translate("MainWindow", ">>>"))
        self.deleteFromTreeWidegt_qpb.setText(_translate("MainWindow", "<<<"))
        self.check_requirement_qpb2.setText(_translate("MainWindow", " 收集需求表格信息"))
        self.lineEdit_4.setText(_translate("MainWindow", "需求表格中的接口列表如下："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "接口布局"))
        self.lineEdit.setText(_translate("MainWindow", "需求表格信息显示："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "需求表格信息"))
        self.headFileProcess_qpb.setText(_translate("MainWindow", "头文件预处理"))
        self.displayfunsInfo_qpb.setText(_translate("MainWindow", "显示头文件列表"))
        item = self.headfilespath_qtb.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "所需头文件列表："))
        item = self.headfilespath_qtb.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "头文件本地路径："))
        self.addenum_qpb.setText(_translate("MainWindow", "补充枚举到需求表格"))
        self.generate_xmlfile_qpb.setText(_translate("MainWindow", "生成xml文件"))
        self.xmlindex_qcb.setItemText(0, _translate("MainWindow", "excelFunsXml"))
        self.xmlindex_qcb.setItemText(1, _translate("MainWindow", "excelXmlForUi"))
        self.generateUniversalvtfile_qpb.setText(_translate("MainWindow", "生成通用代码文件"))
        self.generator_headfiles_qpb.setText(_translate("MainWindow", "生成各页面头文件"))
        self.parse_excelFunsXml_qpb.setText(_translate("MainWindow", "解析xml文件excelFunsXml"))
        self.lineEdit_9.setText(_translate("MainWindow", "生成代码文件："))
        self.parse_excelXmlForUi_qpb.setText(_translate("MainWindow", "解析xml文件excelXmlForUi"))
        self.lineEdit_10.setText(_translate("MainWindow", "生成界面文件"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

